name: ml_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - pip
  - jupyter
  - scikit-learn
  - pip:
      - torch-scatter
      - torch-sparse
      - torch-cluster
      - torch-spline-conv
      - torch-geometric
